### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by thatsprettygood** [Humanoidear/Cleanexxed#4]
What is the difference between Cleanexxed and Cleanexxed Lite?

**Comment by Humanoidear** [comment]
It's following the naming scheme from the official Dolphin theme, Lite's icons are white whilst the regular ones are gray.

**Comment by thatsprettygood** [comment]
I would (suggest) putting that in the readme.

**Comment by Humanoidear** [comment]
Yeah, you're right. I'll add that!
